### ISSUE TITLE
[FIGMA] - Definir ações da postagem do usuário

### ISSUE THREAD

**Issue by BrunoAlm** [Gabi-Code-Projeto-DISCORD/ask_code_frontend#1]
### Protótipo
![image](https://github.com/Gabi-Code-Projeto-DISCORD/ask_code_frontend/assets/65208006/0e454962-6258-46c8-942b-97cb9bdf308f)
https://www.figma.com/file/Ia539Ov4qzyVkZv4W37UsT/AskCode?type=design&node-id=0-1&mode=design&t=HbDktR8A1thASah0-0
### Sugestões:

1. Seguir usuário
2. Bloquear usuário
3. Compartilhar

**Comment by AndreLuisOvidio** [comment]
@GabiiSantana não sei se colocar o botão de seguir nesse ícone é o mais interessante, não será melhor fazer uma página de perfil para o usuário e nessa pagina de seguir colocar o botão de seguir?

alem de que deixar o botão de seguir ai implicaria em deixar o botão de deixar de seguir também nesse local

**Comment by GabiiSantana** [comment]
> @GabiiSantana não sei se colocar o botão de seguir nesse ícone é o mais interessante, não será melhor fazer uma página de perfil para o usuário e nessa pagina de seguir colocar o botão de seguir?
> 
> alem de que deixar o botão de seguir ai implicaria em deixar o botão de deixar de seguir também nesse local

Beleza, vou colocar "ver perfil", mas quando a pessoa quiser parar de seguir vai ter que entrar no perfil do cara, iria ser mais difícil

**Comment by AndreLuisOvidio** [comment]
Aprovado 👍

**Comment by peRodrigues** [comment]
Aprovado 👍
