### ISSUE TITLE
[FIGMA] - Definir componente drawer

### ISSUE THREAD

**Issue by BrunoAlm** [Gabi-Code-Projeto-DISCORD/ask_code_frontend#3]
Discussão sobre o que adicionar/modificar no drawer da aplicação.
   
![image](https://github.com/Gabi-Code-Projeto-DISCORD/ask_code_frontend/assets/65208006/52a32c7c-45ea-46a2-b162-c6eeba4b029f)

![Image](https://github.com/Gabi-Code-Projeto-DISCORD/ask_code_frontend/assets/65208006/9058525b-4e14-4497-9ade-afcac4e3d01b)

https://www.figma.com/file/Ia539Ov4qzyVkZv4W37UsT/AskCode?type=design&node-id=0-1&mode=design&t=pqY7Z2PmZngdJrbb-0

**Comment by AndreLuisOvidio** [comment]
Parece que a imagem quebrou com a migração de repositório, consegue ajustar ela?

**Comment by BrunoAlm** [comment]
> Parece que a imagem quebrou com a migração de repositório, consegue ajustar ela?

ajustado

**Comment by AndreLuisOvidio** [comment]
Aprovado 👍
